### PR TITLE
non-supported-device logic

### PR DESCRIPTION
**Pull request by nicktaras**

### CODE REVIEW

**Comment by oleggrib** [comment]
@nicktaras , please add to the PR setTimeout from my example, in other way it will not work correctly in some cases

**Comment by nicktaras** [comment]
> @nicktaras , please add to the PR setTimeout from my example, in other way it will not work correctly in some cases

Thanks, could you point me to the file with the timeout example or explain the implementation you wish to include e.g. timeout to ensure the item is most likely the last in the queue, or a timeout to hold for x period of time?

Thanks

**Comment by oleggrib** [comment]
https://testshop.antopolbus.rv.ua/agent/agent.html - check this file source code , here is complete working example  @nicktaras

**Comment by oleggrib** [comment]
@nicktaras , please, move all constants from "getBrowserData.ts" inside getBrowserData() method, in this case it will work good

**Comment by nicktaras** [comment]
Example usage:

negotiator = new Client({
      type: 'active',
      issuers: [
        devconConfig
      ],
      options: {
        overlay: {
          openingHeading: "Open a new world of discounts available with your tokens.",
          issuerHeading: "Get discount with Ticket",
          repeatAction: "try again",
          theme: "light",
          position: "bottom-right"
        },
        unSupported: {
          config: {
            iE: false,
            iE9: false,
            edge: false,
            chrome: false,
            phantomJS: false,
            fireFox: false,
            safari: false,
            android: false,
            iOS: false,
            mac: true,
            windows: false,
            touchDevice: false,
            metaMask: false,
            alphaWallet: false,
            mew: false,
            trust: false,
            goWallet: false,
            status: false,
            isImToken: false,
          },
          errorMessage: "This browser cannot yet support token authentication."
        }
      },
      filter: {}
    });

**Comment by micwallace** [comment]
> Example usage: Set any unsupported device to 'true'
> 
> ```js
> negotiator = new Client({
>       type: 'active',
>       issuers: [
>         devconConfig
>       ],
>       options: {
>         overlay: {
>           openingHeading: "Open a new world of discounts available with your tokens.",
>           issuerHeading: "Get discount with Ticket",
>           repeatAction: "try again",
>           theme: "light",
>           position: "bottom-right"
>         },
>         unSupported: {
>           config: {
>             iE: false,
>             iE9: false,
>             edge: false,
>             chrome: false,
>             phantomJS: false,
>             fireFox: false,
>             safari: false,
>             android: false,
>             iOS: false,
>             mac: true,
>             windows: false,
>             touchDevice: false,
>             metaMask: false,
>             alphaWallet: false,
>             mew: false,
>             trust: false,
>             goWallet: false,
>             status: false,
>             isImToken: false,
>           },
>           errorMessage: "This browser cannot yet support token authentication."
>         }
>       },
>       filter: {}
>     });
> ```

@nicktaras is there any reason why all browsers need to be included? Can't we just make these optional and only set unsupported browsers?

**Comment by nicktaras** [comment]
> > Example usage: Set any unsupported device to 'true'
> > ```js
> > negotiator = new Client({
> >       type: 'active',
> >       issuers: [
> >         devconConfig
> >       ],
> >       options: {
> >         overlay: {
> >           openingHeading: "Open a new world of discounts available with your tokens.",
> >           issuerHeading: "Get discount with Ticket",
> >           repeatAction: "try again",
> >           theme: "light",
> >           position: "bottom-right"
> >         },
> >         unSupported: {
> >           config: {
> >             iE: false,
> >             iE9: false,
> >             edge: false,
> >             chrome: false,
> >             phantomJS: false,
> >             fireFox: false,
> >             safari: false,
> >             android: false,
> >             iOS: false,
> >             mac: true,
> >             windows: false,
> >             touchDevice: false,
> >             metaMask: false,
> >             alphaWallet: false,
> >             mew: false,
> >             trust: false,
> >             goWallet: false,
> >             status: false,
> >             isImToken: false,
> >           },
> >           errorMessage: "This browser cannot yet support token authentication."
> >         }
> >       },
> >       filter: {}
> >     });
> > ```
> 
> @nicktaras is there any reason why all browsers need to be included? Can't we just make these optional and only set unsupported browsers?

@micwallace the developer can select which keys they wish to add (CC: @oleggrib).

unSupported: {
          config: {
            iE: true,
            iE9: true
     }
}

This was an array initially e.g. ['ie9', 'MaC'] - but felt this was more error prone and an object with flags would be better managed from the end developer side. 

Thanks for the review, please let me know your thoughts.

**Pull request merged**
