### PR TITLE
Feature/onchain module optimisations

### PR DESCRIPTION
**Pull request by nicktaras**

### CODE REVIEW

**Comment by nicktaras** [comment]
Hi Miccy, I've merged both of the PR's into this branch. 

I've resolved the conflicts, but needs more changes to full merge.

**Review by micwallace — APPROVED** [review]
Approving for merge into main.

**Comment by micwallace** [comment]
We really need to get this linting setup sorted. Very hard to see actual changes with changes in spacing/indents. Also it seems a lot of my changes have been reverted. Did you pull the latest changes before commiting?

**Comment by nicktaras** [comment]
@micwallace yep I pulled the latest changes (carefully merged etc). There was one change I thought wasn't the most optimised where I could see 2 for loops to apply the API keys to the onChain config. So adjusted this to be optimised in the sense it just writes the config at the constructor stage. We can adjust if we want etc. 

Really great job on re working the module including http requests, this is such much better and easy to follow. 

https://github.com/TokenScript/token-negotiator/discussions/171 - for Linting we've started this Github discussion page.
Let me know your thoughts on this and let's implement the changes. In the meantime, let's lint the code using Prettier which seems to use the standard / be the standard from looking across various tools.

**Comment by micwallace** [comment]
Good call on that @nicktaras better initialised in the constructor.

**Pull request merged**
