### PR TITLE
fix: SVG fill color not working when included as a background

### PR DESCRIPTION
**Pull request by micwallace**
Use mask image instead to control color for dark/light theme

### CODE REVIEW

**Comment by micwallace** [comment]
@snowwhitedev Can you please check this for me when you get a chance. SVG fill color wasn't working for me when included as a background image.

**Comment by snowwhitedev** [comment]
> @snowwhitedev Can you please check this for me when you get a chance. SVG fill color wasn't working for me when included as a background image.

@micwallace Cool. I tried to run your work on my local(windows chrome browser). but it seems it's not expected. :)
I am attaching simple video. (I sent it in discord, too)

https://user-images.githubusercontent.com/58669769/218137372-f6521738-3f58-45e2-aeaf-4faa48cccf32.mp4

**Review by snowwhitedev — CHANGES_REQUESTED** [review]
could you check my video?

**Comment by nicktaras** [comment]
> could you check my video?

@micwallace can you help get back to on his questions @snowwhitedev?

Thanks guys

**Comment by nicktaras** [comment]
> > could you check my video?
> 
> @micwallace can you help get back to @snowwhitedev on his questions?
> 
> Thanks guys

**Comment by micwallace** [comment]
@snowwhitedev @nicktaras This should be working now. It fixed the issue in Chrome Linux.

**Comment by micwallace** [comment]
This also fixes an issue where the close animation sometimes plays when loading the page.

**Review by snowwhitedev — APPROVED** [review]
Looks good. Btw could we improve sonar issues? or is it better to do it in other branch?

**Pull request merged**
