### PR TITLE
Fix: url namespace backward compatibility

### PR DESCRIPTION
**Pull request by micwallace**
Ensure all v2 versions of client & outlet are cross compatible

### CODE REVIEW

**Review by oleggrib — APPROVED** [review]
Looks great

**Comment by nicktaras** [comment]
@oleggrib could you help smoke test this and merge. 

Thanks

**Comment by oleggrib** [comment]
I am adding some cross-versions tests to make sure all works good @nicktaras

**Comment by oleggrib** [comment]
by the way - TN 2.0 doesnt support redirect flow, so 2.0 and 2.5 is not compatable at all 
@micwallace @nicktaras

**Review by oleggrib — APPROVED** [review]

**Comment by oleggrib** [comment]
I replaced document.location to window.location because window.location is read/write, so its better for tests, also  window.location works same way in all browsers, while document.location acts different in browsers
https://www.geeksforgeeks.org/javascript-window-location-and-document-location-objects/
@micwallace @snowwhitedev @nicktaras 

also I fixed bug with permissions, thanks to the cross-version tests

**Comment by nicktaras** [comment]
Approved. 

Reviewed and smoke tested on desktop browsers.

**Pull request merged**
