### PR TITLE
Feature/release prep 2.2.0

### PR DESCRIPTION
**Pull request by nicktaras**

### CODE REVIEW

**Review by snowwhitedev — APPROVED** [review]
Looks good.

**Comment by oleggrib** [comment]
@nicktaras REDIRECT flow will be added to the next release , right?

**Comment by nicktaras** [comment]
> @nicktaras REDIRECT flow will be added to the next release , right?

Yes let's bring this into the next release soon.

**Review by oleggrib — APPROVED** [review]
looks good, thank you

**Review by micwallace — APPROVED** [review]
Looks good to me @nicktaras

**Review by BankiLouis — APPROVED** [review]

**Pull request merged**
