### PR TITLE
FEAT: Added check for non supported browsers/userAgents

### PR DESCRIPTION
**Pull request by BankiLouis**
This PR has updates for checking nonsupported browsers/platforms.

### CODE REVIEW

**Review by micwallace — CHANGES_REQUESTED** [review]
Hey @BankiLouis 

Good work on your first PR for negotiator. 
There is one thing in these changes that I think should be optimized:

The functions checkBrowserSupport & isUserAgentSupported are very similar. Rather than having checkBrowserSupport in Client.ts, merge it with the existing isUserAgentSupported function in isSupported.ts. isUserAgentSupported is already used in Client for the authenticate function.

**Comment by nicktaras** [comment]
> Hey @BankiLouis
> 
> Good work on your first PR for negotiator. There is one thing in these changes that I think should be optimized:
> 
> The functions checkBrowserSupport & isUserAgentSupported are very similar. Rather than having checkBrowserSupport in Client.ts, merge it with the existing isUserAgentSupported function in isSupported.ts. isUserAgentSupported is already used in Client for the authenticate function.

Really point @micwallace.

We haven't release 2.0 yet, giving an opportunity for us to re-work the unSupported config.

How about we, adjust the following structure of the new TN config from:

````
client = {
unSupportedUserAgent: {
        config: {
            // options to test against : ["iE", "iE9", "edge", "chrome", "phantomJS", "fireFox", "safari", "android", "iOS", "mac", "windows", "webView", "touchDevice", "metaMask", "alphaWallet", "mew", "trust", "goWallet", "status", "imToken", "metaMaskAndroid", "alphaWalletAndroid", "mewAndroid", "imTokenAndroid"];
            metaMaskAndroid: true,
            alphaWalletAndroid: true,
            mewAndroid: true,
            imTokenAndroid: true,
        }
    }
}
````

to:

````
client = {
unSupportedUserAgent: {
        authentication: {
            config: {
                metaMaskAndroid: true,
                alphaWalletAndroid: true,
                mewAndroid: true,
                imTokenAndroid: true,
            },
           warningMessage: '....'
        },
        full: {
            config: {
                iE: true,
                iE9: true,
            },
           warningMessage: '....'
        }
    }
}
````

This should allow us to use the same logic for both use cases.

**Comment by micwallace** [comment]
Is there any reason to have it as an option? Why not hard-code it if we are not supporting IE in any circumstances.

**Comment by BankiLouis** [comment]
> Hey @BankiLouis
> 
> Good work on your first PR for negotiator. There is one thing in these changes that I think should be optimized:
> 
> The functions checkBrowserSupport & isUserAgentSupported are very similar. Rather than having checkBrowserSupport in Client.ts, merge it with the existing isUserAgentSupported function in isSupported.ts. isUserAgentSupported is already used in Client for the authenticate function.

Thanks @micwallace, yeah I think that will be ideal. Let me get on that.

**Review by micwallace — CHANGES_REQUESTED** [review]

**Review by micwallace — APPROVED** [review]

**Pull request merged**
