### PR TITLE
feat: multi-blockchain & wallet support - UX

### PR DESCRIPTION
**Pull request by micwallace**
Implements TKS-899 & TKS-900

- Add wallet manager view & button to access
- Add exception to show select-wallet screen for specific blockchain w hen "load" is triggered for a blockchain that does not currently have a wallet connected.

### CODE REVIEW

**Comment by nicktaras** [comment]
Hi Miccy,

Can you create Jira tickets for this work to include the reason of the change and acceptance criteria. 

Splitting this down into smaller more code reviewable changes per delivery item. 

Really appreciate the effort when completing many feature, but working this way creates a lot of work for a reviewer and allows for un-known features to enter our code base. 

Where this PR seems to address some planned Jira tasks including one that is assigned to me to complete around correcting  the interfaces with integration with Brand Connector.

https://smarttokenlabs.atlassian.net/jira/software/c/projects/TKS/boards/13?modal=detail&selectedIssue=TKS-579&quickFilter=47&assignee=61bad12c91c049006fc86fcd

cc: @tcglam , @AW-STJ

**Comment by micwallace** [comment]
Hey @nicktaras will do.

Since this is a rather large ticket, the idea here is to break it up into smaller parts. For instance Oleg said he's like to work on authentication for solana & flow. These small parts can be merged into this branch and when ready, released in one go.

**Comment by nicktaras** [comment]
> 

"Hey @nicktaras will do.

Since this is a rather large ticket, the idea here is to break it up into smaller parts. For instance Oleg said he's like to work on authentication for solana & flow. **These small parts can be merged into this branch and when ready, released in one go**."

This PR is too large to merge as one change. Please work with @oleggrib to merge branches with jira tickets that describe the work / features being introduced to the product. 

This to:

- Stop changes reaching production that haven't been planned
- give transparency of the work / features being introduced at an early stage
- reduce the risk of developers reviewing several changes in one, and missing mistakes in the code 
- give our QA team insight into the work being done and how they can test it / and the stage it's in
- give transparency to the business, to understand the changes and if they are aligned to the roadmap
- to stop duplication and overriding of assigned work between our team / team effort & collaboration being key to our delivery

cc: @AW-STJ, @tcglam

**Comment by AW-STJ** [comment]
> Can you create seperate Jira tickets for this work to include the reason for each of the changes with acceptance criteria.

Let us follow this guidance. Tracking the changes in JIRA helps the team to be aware of the changes being worked on and to plan on what needs to go in to the release and what should not. 

Also we had agreed on this as a principle for making changes:
> Small, atomic PRs that only do one thing 
https://www.notion.so/stormbirdlabs/Software-Development-Operating-Principles-849e9da54d034a638c506a2854f84685?pvs=4#33cfe9312c6143518e3f6960afb3a788

**Comment by micwallace** [comment]
Hey @nicktaras @AW-STJ 

We can definitely release this in stages, this PR is basically here to track compatibility, and for devs to work off for other tasks contained in this feature before the first PR is merged. I will create another PR with the initial core changes and exclude wallet manager UI

**Comment by micwallace** [comment]
Here is the initial PR: https://github.com/TokenScript/token-negotiator/pull/611

**Comment by nicktaras** [comment]
Closing this PR. I understand there was a duplicate ticket that was approved around this.

To proceed with additions to the multi-wallet feature let's catch up together with Lucas and ensure we are meeting all the initial plans for this feature in the backlog and any UI / UX suggestions from Lucas.

**Comment by micwallace** [comment]
@nicktaras Some changes included in this PR were moved to a new PR (core changes).

This PR/branch now only adds the UX for multi-wallet connection & management so can be left open.

**Comment by nicktaras** [comment]
> @nicktaras Some changes included in this PR were moved to a new PR (core changes).
> 
> This PR/branch now only adds the UI for multi-wallet connection & management so can be left open. Let me know when this is ready to be added and I will rebase and retest.

Hi @micwallace,

Can you help clarify where the requirements are for this ticket to review against in Jira.

**Comment by AW-STJ** [comment]
@nicktaras and Basti can make the final call on what goes in and what does not.

**Comment by BastianAlpha** [comment]
I have not been across this work. I can see the tickets TKS-900 and TKS-999 in Jira which describe the work.
The work seem to make sense but I have not been able to see the UX and do not know if / how this would impact all the UI/UX work that the design team is doing at the moment. 

I am not able to make an assessment at this stage. Can i see a screenshot or some reference and can we confirm that this has no impact on the design uplift Lucas and team are doing?
cc @micwallace  @nicktaras  @AW-STJ

**Comment by nicktaras** [comment]
> 

Hi @micwallace,

From investigating this today, I'll re-close this ticket for now for us to come back to.

The reasons are:

- This feature requirement was marked to be on hold in Jira with no assigned release version
- The original ticket for this task hadn't been brought into scope for development yet
- We are unsure of the requirement origin where the full implementation details were still to be derived & defined for development readiness

Thanks

Nick

cc: @BastianAlpha, @AW-STJ, @tcglam

**Comment by micwallace** [comment]
@nicktaras Please just leave it open so it doesn't drop off the radar. It doesn't have to be merged anytime soon, but it will be important for true multi-blockchain support.

**Pull request closed without merging**
